// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpKAu0aU90yjgbZmGMdRy9anSHczZ2I8U',
    appId: '1:1001165366805:web:09ae3e628eef3ad2e4101c',
    messagingSenderId: '1001165366805',
    projectId: 'dearme-b88e7',
    authDomain: 'dearme-b88e7.firebaseapp.com',
    storageBucket: 'dearme-b88e7.appspot.com',
    measurementId: 'G-01XDWX8DWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaBZLgZvC05TiD2xZR5dqiXJie6vpbx58',
    appId: '1:360411427664:android:f6fcc2be38071bd3613255',
    messagingSenderId: '360411427664',
    projectId: 'soulna-1170e',
    storageBucket: 'soulna-1170e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWfG70fZaLpai4bwaYXBdZp4sdHKAWBZ4',
    appId: '1:360411427664:ios:eb599285819c56d5613255',
    messagingSenderId: '360411427664',
    projectId: 'soulna-1170e',
    storageBucket: 'soulna-1170e.appspot.com',
    androidClientId: '360411427664-si7pk11v099jbfgonds94v81o8t97hjg.apps.googleusercontent.com',
    iosClientId: '360411427664-f6rgvvm0smkgint4des6kpg43sb4em0t.apps.googleusercontent.com',
    iosBundleId: 'com.modawn.soulna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7iPSwjuJx1OlJgwhKTDiEAPSQJ_szaXg',
    appId: '1:1001165366805:ios:b958c70ba4bd4866e4101c',
    messagingSenderId: '1001165366805',
    projectId: 'dearme-b88e7',
    storageBucket: 'dearme-b88e7.appspot.com',
    androidClientId: '1001165366805-37fepqumcvvhg1n3a8pmgafon47g9mv3.apps.googleusercontent.com',
    iosClientId: '1001165366805-ctf74b7j47mvb7j0sicb7f4fna9433fk.apps.googleusercontent.com',
    iosBundleId: 'com.example.dearMeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpKAu0aU90yjgbZmGMdRy9anSHczZ2I8U',
    appId: '1:1001165366805:web:eb34346cfcc81495e4101c',
    messagingSenderId: '1001165366805',
    projectId: 'dearme-b88e7',
    authDomain: 'dearme-b88e7.firebaseapp.com',
    storageBucket: 'dearme-b88e7.appspot.com',
    measurementId: 'G-9NBTGM5936',
  );
}